### ISSUE TITLE
debug issue

### ISSUE THREAD

**Issue by HMX2013** [url-kaist/TRAVEL#2]
Thanks for your open source. The debug code seems to be incompleted. Noted that some related code has been commented. After uncomment these code, I still can not get the right result. I wonder if this part hasn't been completed yet.

![image](https://user-images.githubusercontent.com/105980724/197489007-11d5bd69-ce6e-437f-a4f4-df4f69ed51ae.png)

**Comment by Minho5Oh** [comment]
Oh, i am sorry about that.
I will update about that codes.
Anyway, did you debug TGS module or AOS module? Please let me know that.
