### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 4555ch** [url-kaist/TRAVEL#3]
de.h: 没有那个文件或目录
 #include "travel/node.h"
您好，在您的仓里面没有头文件，可以发一下吗谢谢

**Comment by fatrybl** [comment]
Hello, i have the same issue while catkin_make

**Comment by Minho5Oh** [comment]
In msg folder, there is a "node.msg" file.
If you can not compile, you should check your "CMakeLists.txt"

**Comment by 4555ch** [comment]
Glad to receive your reply ，your papers are of a high standard and Korean friends are very smart.thx



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Minho ***@***.***&gt;; 
发送时间: 2023年2月18日(星期六) 晚上6:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [url-kaist/TRAVEL] Help (Issue #3)





 
In msg folder, there is a "node.msg" file.
 If you can not compile, you should check your "CMakeLists.txt"

**Comment by Minho5Oh** [comment]
OMG... Thank you so much for those compliments.

**Comment by 4555ch** [comment]
Thank you for seeing this letter in your busy schedule, I would like to add some clustering code to your paper patchwork, the clustering of obstacles after one side has been divided, where should I add it? Can you give me some advice?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "url-kaist/TRAVEL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 晚上9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [url-kaist/TRAVEL] Help (Issue #3)





 
OMG... Thank you so much for those compliments.

**Comment by Minho5Oh** [comment]
> May I ask whether the Lmax and Lmin in the patch of the paper refer to the circumference of the concentric circle or the radius of the concentric circle?&nbsp;Looking forward to your answer
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Minho ***@***.***&gt;; 发送时间: 2023年2月20日(星期一) 晚上9:57 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [url-kaist/TRAVEL] Help (Issue #3) OMG... Thank you so much for those compliments. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Do you mean "L_max and L_min" from Pathcwork (https://github.com/LimHyungTae/patchwork)?
Hmmm..... anyway, L_max and L_min is the radial boundary of the patches. You can find that on "B. Concentric Zone Model, page. 3"

**Comment by Minho5Oh** [comment]
> Thank you for seeing this letter in your busy schedule, I would like to add some clustering code to your paper patchwork, the clustering of obstacles after one side has been divided, where should I add it? Can you give me some advice?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "url-kaist/TRAVEL" ***@***.***&gt;; 发送时间:&nbsp;2023年2月20日(星期一) 晚上9:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [url-kaist/TRAVEL] Help (Issue #3) OMG... Thank you so much for those compliments. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

TGS and AOS of TRAVEL can be used with each function.
`
travel_ground_seg->estimateGround(*filtered_pc, *ground_pc, *nonground_pc, ground_seg_time);
travel_object_seg->segmentObjects(nonground_pc, labeled_pc);
`
Therefore, if you want to use "AOS" module after "Patchwork" operation, you can use "travel_object_seg->segmentObjects(nonground_pc,label_pc)" with nonground data among Patchwork results.

**Comment by 4555ch** [comment]
답장을 보내 주셔서 다시 한 번 감사드립니다. 이전에 신문을 주의 깊게 읽지 못한 점 정말 죄송합니다. 건강과 행복을 기원합니다!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Minho ***@***.***&gt;; 
发送时间: 2023年3月26日(星期天) 晚上6:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [url-kaist/TRAVEL] Help (Issue #3)





  
May I ask whether the Lmax and Lmin in the patch of the paper refer to the circumference of the concentric circle or the radius of the concentric circle?&nbsp;Looking forward to your answer
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Minho @.&gt;; 发送时间: 2023年2月20日(星期一) 晚上9:57 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [url-kaist/TRAVEL] Help (Issue #3) OMG... Thank you so much for those compliments. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Do you mean "L_max and L_min" from Pathcwork (https://github.com/LimHyungTae/patchwork)?
 Hmmm..... anyway, L_max and L_min is the radial boundary of the patches. You can find that on "B. Concentric Zone Model, page. 3"

**Comment by 4555ch** [comment]
Sorry to bother you again, I still have a question about the thesis patchwork: why there is a straight line in the original laser point cloud when I start the launch file, how do you deal with it? Looking forward to your reply, thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "url-kaist/TRAVEL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月26日(星期天) 晚上6:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [url-kaist/TRAVEL] Help (Issue #3)





  
May I ask whether the Lmax and Lmin in the patch of the paper refer to the circumference of the concentric circle or the radius of the concentric circle?&nbsp;Looking forward to your answer
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Minho @.&gt;; 发送时间: 2023年2月20日(星期一) 晚上9:57 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [url-kaist/TRAVEL] Help (Issue #3) OMG... Thank you so much for those compliments. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Do you mean "L_max and L_min" from Pathcwork (https://github.com/LimHyungTae/patchwork)?
 Hmmm..... anyway, L_max and L_min is the radial boundary of the patches. You can find that on "B. Concentric Zone Model, page. 3"
