### ISSUE TITLE
The ring number sames not right

### ISSUE THREAD

**Issue by HMX2013** [url-kaist/TRAVEL#7]
Thanks for your work.
I used the same color to represent the point with the same ring number, but the result was not correct.  The function getRowIdx() seems not very accurate. I think the reason is the distortion of lidar. Besides, I think horz_scan of semantic kitti dataset should be 2048 instead of 4500.

<img width="721" alt="屏幕截图 2023-02-14 220810" src="https://user-images.githubusercontent.com/105980724/218762298-144b6b5e-7f7f-45f0-aaca-1d1892d7b94a.png">

<img width="845" alt="屏幕截图 2023-02-14 220129" src="https://user-images.githubusercontent.com/105980724/218760835-a4f3eee8-897b-4bd6-86c6-e60f7d5d47e3.png">

**Comment by Minho5Oh** [comment]
Thank you for your interest in our research.
As you said, getRowIdx() in our code only works if the horizontal angle resolution is uniform. 
In other words, for data with non-uniform angle resolution, such as kitti data, it may be better to use ring information.
In this case, I recommend you to use another function "int getRowIdx(T pt, vector<float> vert_angles) " with initializing "vector<float> vert_angles_". This fuction and vector are already defined in "aos.hpp", so you can change.

It is also true that kitti data itself has inaccurate data for lidar deskewing.
