### ISSUE TITLE
The sum of ground points and non-ground points is not equal to the number of points in the original point cloud

### ISSUE THREAD

**Issue by qiaozhijian** [url-kaist/TRAVEL#9]
The sum of ground points and non-ground points is not equal to the number of points in the original point cloud. 

For example, seq 00, frame 0
**raw pc** size: 124668 
**travel:**
pc_ground size: 75306 
pc_non_ground size: 53565 
sum: 128871
where 128871 > 124668

**Comment by Minho5Oh** [comment]
You need to modify the "segmentTGFGround" function as follow~!! 
`
        void segmentTGFGround(const TriGridField<PointType>& tgf_in, 
                        pcl::PointCloud<PointType>& ground_cloud_out, 
                        pcl::PointCloud<PointType>& nonground_cloud_out,
                        pcl::PointCloud<PointType>& obstacle_cloud_out,
                        pcl::PointCloud<PointType>& outlier_cloud_out) {
            ground_cloud_out.clear();
            nonground_cloud_out.clear();
            obstacle_cloud_out.clear();

            for (int r_i = 0; r_i < rows_; r_i++){
            for (int c_i = 0; c_i < cols_; c_i++){
            for (int s_i = 0; s_i < tgf_in[r_i][c_i].size(); s_i++) {
                if (!tgf_in[r_i][c_i][s_i].is_curr_data) {
                    continue;
                }
                ptCloud_nodewise_ground_.clear();
                ptCloud_nodewise_nonground_.clear();
                ptCloud_nodewise_outliers_.clear();
                ptCloud_nodewise_obstacle_.clear();
                if (tgf_in[r_i][c_i][s_i].node_type == GROUND) {
                    segmentNodeGround(tgf_in[r_i][c_i][s_i], ptCloud_nodewise_ground_, ptCloud_nodewise_nonground_, ptCloud_nodewise_obstacle_, ptCloud_nodewise_outliers_);
                } else {
                    ptCloud_nodewise_nonground_ = tgf_in[r_i][c_i][s_i].ptCloud;
                    ptCloud_nodewise_obstacle_ = tgf_in[r_i][c_i][s_i].ptCloud;
                }
                ground_cloud_out += ptCloud_nodewise_ground_;
                nonground_cloud_out += ptCloud_nodewise_nonground_;
                outlier_cloud_out += ptCloud_nodewise_outliers_;
                obstacle_cloud_out += ptCloud_nodewise_obstacle_;
            }
            }
            }

            return;
        };
`

**Comment by Minho5Oh** [comment]
If you modify that function, then i will be same.....! I hope.... kkkkk

**Comment by qiaozhijian** [comment]
Thank you, nice work~
